name: build
on:
  push:
    branches:
      - main
jobs:
  package-web-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: zip --junk-paths asda-helper.zip $GITHUB_WORKSPACE/manifest.json $GITHUB_WORKSPACE/asda.js
      - uses: actions/upload-artifact@v2.2.0
        with:
          name: web-extension
          path: asda-helper.zip
          
